import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { stringify as stringifyYaml } from "yaml";
import { CARD_SLUG, type AgentDef, type HarnessBundle, type WikiPage } from "./schema.js";

// The two interop targets M4 Task 5 produces. `agents-md` is the emerging
// cross-tool convention (a single project-root file any agent CLI can read);
// `claude-subagents` is Claude Code's own per-agent subagent format. Both
// are pure derivations of an already-generated, already-validated
// HarnessBundle — neither format is ever the source of truth, and neither
// write is transactional the way store.ts's writeHarness is (see that
// module's header comment): these are user-facing export targets a human
// may hand-edit afterward, not the harness itself.
export type HarnessExportFormat = "agents-md" | "claude-subagents" | "opencode";

export interface HarnessExportResult {
  files: string[];
}

// Shown at the top of AGENTS.md (and, implicitly, is why claude-subagents
// prompts don't repeat it per-file — AGENTS.md is the one place a human is
// expected to read end to end) whenever the harness hasn't yet cleared its
// eval gate (spec §12.1 ETH hazard gate; M6). `manifest.verification.evals`
// starts "pending" at generation time and is never assumed "pass" — this
// caveat is the harness's own admission that its agent prompts and routing
// are unverified until the eval loop says otherwise.
const UNVERIFIED_CAVEAT =
  '> **UNVERIFIED**: this harness has not yet passed its eval gate (`manifest.verification.evals` is not `"pass"`). Treat the agent roster, prompts, and routing below as unverified until `engine.harness.generate`’s eval loop confirms they do not regress quality versus an all-frontier baseline.';

// Same caveat, but as a YAML COMMENT for claude-subagents' per-agent
// frontmatter (see renderSubagentMd below) — a user who exports ONLY
// subagents (never AGENTS.md) would otherwise get trusted-looking files
// with no ETH-gate caveat anywhere in them. A comment, not a real
// frontmatter field, so it never pollutes the agent's actual config.
const UNVERIFIED_SUBAGENT_COMMENT =
  "# UNVERIFIED: this harness has not passed evals (openfusion M6); review before trusting";

function findPage(bundle: HarnessBundle, slug: string): WikiPage | undefined {
  return bundle.pages.find((p) => p.slug === slug);
}

// Table cells are `|`-delimited — an unescaped `|` or embedded newline in
// model-generated text (role, taskClasses, etc.) would otherwise split a
// row in two or break the table entirely. Escapes both hazards; applied to
// every dynamic (model-sourced) cell value in renderAgentsMd's roster table.
function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r\n|\r|\n/g, " ");
}

// Claude Code's own `model:` frontmatter field expects one of ITS model
// aliases (sonnet/opus/haiku/inherit) — our worker models (open-model
// kind/model pairs, or the literal "frontier") don't map onto that set, so
// rather than emit a value Claude Code would reject or silently
// misinterpret, the routing decision is surfaced as a comment a human (or a
// future importer) can read and act on manually.
function renderModelHint(agent: AgentDef): string {
  return agent.model === "frontier" ? "frontier" : `${agent.model.kind}/${agent.model.model}`;
}

function renderPageSection(page: WikiPage | undefined, missingLabel: string): string {
  if (page === undefined) return `_No ${missingLabel} wiki page available._`;
  return `${page.digest}\n\n${page.body.trim()}`;
}

// `<projectDir>/AGENTS.md` — a single project-root file summarizing the
// generated harness for any agent CLI that reads the AGENTS.md convention.
// Section order and content are pinned by the M4 Task 5 brief, extended by
// the wiki-project-card work (spec §6): an approved Project Card section
// leads the file when present (gated on both the CARD_SLUG page and
// manifest.verification.card === "approved" — see the card-led export gate
// below), THEN project summary (architecture page), build/test commands
// (build-and-test page), conventions (conventions page), then the agent
// roster table. The UNVERIFIED caveat is emitted directly under the title
// whenever `manifest.verification.evals !== "pass"` so it's the first thing
// a reader sees, not buried after the roster — independent of, and
// unaffected by, whether the card section is present.
function renderAgentsMd(bundle: HarnessBundle): string {
  const lines: string[] = [];
  lines.push("# AGENTS.md");
  lines.push("");
  lines.push(
    "Generated by OpenFusion harness generation from this repository — a project-dedicated wiki, specialist agent roster, and routing policy. Regenerate via `engine.harness.generate` (or edit through the Harness editor) rather than hand-editing this file directly.",
  );
  lines.push("");

  if (bundle.manifest.verification.evals !== "pass") {
    lines.push(UNVERIFIED_CAVEAT);
    lines.push("");
  }

  // Card-led export (spec §6): both the wiki page (CARD_SLUG) AND
  // manifest.verification.card === "approved" must hold — the same
  // both-exist discipline orchestrate.ts's buildWorkerContext uses for
  // worker-prompt injection. Only then does the card lead the file, ahead of
  // "## Project summary". A draft card, or an "approved" manifest flag with
  // no matching page (e.g. hand-edited away), gets NO section here: the
  // export stays byte-identical to a harness with no card at all — never a
  // degraded/partial rendering of its own. This gate is independent of the
  // UNVERIFIED caveat above (which gates harness trust, not card trust).
  const card = findPage(bundle, CARD_SLUG);
  if (card !== undefined && bundle.manifest.verification.card === "approved") {
    const CARD_DIRECTIVE =
      "> Commands here are statically extracted, not execution-verified; if one fails, treat `package.json` scripts / CI workflows as ground truth.";
    lines.push("## Project card");
    lines.push("");
    lines.push(CARD_DIRECTIVE);
    lines.push("");
    lines.push(card.digest);
    lines.push("");
    lines.push(card.body.trim());
    lines.push("");
  }

  lines.push("## Project summary");
  lines.push("");
  lines.push(renderPageSection(findPage(bundle, "architecture"), "architecture"));
  lines.push("");

  lines.push("## Build & test");
  lines.push("");
  lines.push(renderPageSection(findPage(bundle, "build-and-test"), "build-and-test"));
  lines.push("");

  lines.push("## Conventions");
  lines.push("");
  lines.push(renderPageSection(findPage(bundle, "conventions"), "conventions"));
  lines.push("");

  lines.push("## Agent roster");
  lines.push("");
  lines.push("| Name | Role | Task classes | Model |");
  lines.push("| --- | --- | --- | --- |");
  for (const agent of bundle.agents) {
    const name = escapeCell(agent.name);
    const role = escapeCell(agent.role);
    const taskClasses = escapeCell(agent.taskClasses.join(", "));
    const model = escapeCell(renderModelHint(agent));
    lines.push(`| ${name} | ${role} | ${taskClasses} | ${model} |`);
  }
  lines.push("");

  return lines.join("\n");
}

async function exportAgentsMd(projectDir: string, bundle: HarnessBundle): Promise<HarnessExportResult> {
  const filePath = path.join(projectDir, "AGENTS.md");
  await writeFile(filePath, renderAgentsMd(bundle), "utf8");
  return { files: [path.relative(projectDir, filePath)] };
}

// Read-only by default: an exported subagent runs on an open worker model
// under a specialist prompt this pipeline generated but has not yet
// eval-gated (see UNVERIFIED_CAVEAT above) — it should be able to explore
// the project, not mutate it, until a human explicitly widens its tools in
// Claude Code's own subagent config.
const READ_ONLY_TOOLS_LINE = "Read, Grep, Glob";

// `<projectDir>/.claude/agents/<name>.md` per agent — Claude Code's native
// subagent format: YAML frontmatter (name, description, a read-only tools
// default, and the model hint AS A COMMENT — see renderModelHint) followed
// by a blank line, the agent's own prompt, and a digest of every wiki page
// in the bundle so the subagent carries the same project context it would
// have had inside OpenFusion's own orchestrator, without requiring the wiki
// MCP server to be running.
function renderSubagentMd(agent: AgentDef, bundle: HarnessBundle): string {
  const frontmatter = stringifyYaml({
    name: agent.name,
    description: agent.description,
    tools: READ_ONLY_TOOLS_LINE,
  });
  const unverifiedComment =
    bundle.manifest.verification.evals !== "pass" ? `${UNVERIFIED_SUBAGENT_COMMENT}\n` : "";
  const header = `---\n${frontmatter}${unverifiedComment}# suggested worker: ${renderModelHint(agent)}\n---\n`;

  const body: string[] = [agent.prompt.trim(), "", "## Project wiki digest", ""];
  for (const page of bundle.pages) {
    body.push(`### ${page.title}`, "", page.digest, "");
  }

  return `${header}\n${body.join("\n").trimEnd()}\n`;
}

async function exportClaudeSubagents(projectDir: string, bundle: HarnessBundle): Promise<HarnessExportResult> {
  const dir = path.join(projectDir, ".claude", "agents");
  await mkdir(dir, { recursive: true });
  const files: string[] = [];
  for (const agent of bundle.agents) {
    const filePath = path.join(dir, `${agent.name}.md`);
    await writeFile(filePath, renderSubagentMd(agent, bundle), "utf8");
    files.push(path.relative(projectDir, filePath));
  }
  return { files };
}

/**
 * OpenCode-style project config: opencode.json with per-agent model
 * bindings + instruction pointers. Pure derivation of the harness bundle.
 */
function renderOpencodeJson(bundle: HarnessBundle): string {
  const agents: Record<string, unknown> = {};
  for (const agent of bundle.agents) {
    const model =
      agent.model === "frontier"
        ? { provider: "frontier", model: "default" }
        : {
            provider: agent.model.kind,
            model: agent.model.model,
            ...(agent.model.providerId !== undefined ? { providerId: agent.model.providerId } : {}),
            ...(agent.model.family !== undefined ? { family: agent.model.family } : {}),
            ...(agent.model.dialectPack !== undefined
              ? { dialectPack: agent.model.dialectPack }
              : {}),
          };
    agents[agent.name] = {
      description: agent.description,
      prompt: agent.prompt,
      taskClasses: agent.taskClasses,
      model,
    };
  }

  const config = {
    $schema: "https://opencode.ai/config.json",
    // OpenFusion provenance — not load-bearing for OpenCode itself.
    openfusion: {
      schemaVersion: bundle.manifest.schemaVersion,
      harnessProfile: bundle.manifest.harnessProfile ?? "openfusion-native",
      familyCatalogVersion: bundle.manifest.familyCatalogVersion,
      dialectPackVersion: bundle.manifest.dialectPackVersion,
      evals: bundle.manifest.verification.evals,
      note:
        bundle.manifest.verification.evals !== "pass"
          ? "UNVERIFIED: harness has not passed evals"
          : undefined,
    },
    default_agent: bundle.routing.defaults.agent,
    agents,
    instructions: ["AGENTS.md"],
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

async function exportOpencode(projectDir: string, bundle: HarnessBundle): Promise<HarnessExportResult> {
  // Always emit AGENTS.md alongside opencode.json so OpenCode has the card-
  // led project instructions OpenFusion already generates.
  const agentsResult = await exportAgentsMd(projectDir, bundle);
  const opencodePath = path.join(projectDir, "opencode.json");
  await writeFile(opencodePath, renderOpencodeJson(bundle), "utf8");
  return {
    files: [...agentsResult.files, path.relative(projectDir, opencodePath)],
  };
}

// Entry point for `engine.harness.export` (methods.ts). Callers are
// responsible for loading and structurally validating the bundle first
// (loadHarness + validateHarness) — this function assumes `bundle` is
// already known-good and does no re-validation of its own.
export async function exportHarness(
  projectDir: string,
  bundle: HarnessBundle,
  format: HarnessExportFormat,
): Promise<HarnessExportResult> {
  if (format === "agents-md") return exportAgentsMd(projectDir, bundle);
  if (format === "opencode") return exportOpencode(projectDir, bundle);
  return exportClaudeSubagents(projectDir, bundle);
}
