import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { stringify as stringifyYaml } from "yaml";
import type { AgentDef, HarnessBundle, WikiPage } from "./schema.js";

// The two interop targets M4 Task 5 produces. `agents-md` is the emerging
// cross-tool convention (a single project-root file any agent CLI can read);
// `claude-subagents` is Claude Code's own per-agent subagent format. Both
// are pure derivations of an already-generated, already-validated
// HarnessBundle — neither format is ever the source of truth, and neither
// write is transactional the way store.ts's writeHarness is (see that
// module's header comment): these are user-facing export targets a human
// may hand-edit afterward, not the harness itself.
export type HarnessExportFormat = "agents-md" | "claude-subagents";

export interface HarnessExportResult {
  files: string[];
}

// Shown at the top of AGENTS.md (and, implicitly, is why claude-subagents
// prompts don't repeat it per-file — AGENTS.md is the one place a human is
// expected to read end to end) whenever the harness hasn't yet cleared its
// eval gate (spec §12.1 ETH hazard gate; M6). `manifest.verification.evals`
// starts "pending" at generation time and is never assumed "pass" — this
// caveat is the harness's own admission that its agent prompts and routing
// are unverified until the eval loop says otherwise.
const UNVERIFIED_CAVEAT =
  '> **UNVERIFIED**: this harness has not yet passed its eval gate (`manifest.verification.evals` is not `"pass"`). Treat the agent roster, prompts, and routing below as unverified until `engine.harness.generate`’s eval loop confirms they do not regress quality versus an all-frontier baseline.';

function findPage(bundle: HarnessBundle, slug: string): WikiPage | undefined {
  return bundle.pages.find((p) => p.slug === slug);
}

// Claude Code's own `model:` frontmatter field expects one of ITS model
// aliases (sonnet/opus/haiku/inherit) — our worker models (open-model
// kind/model pairs, or the literal "frontier") don't map onto that set, so
// rather than emit a value Claude Code would reject or silently
// misinterpret, the routing decision is surfaced as a comment a human (or a
// future importer) can read and act on manually.
function renderModelHint(agent: AgentDef): string {
  return agent.model === "frontier" ? "frontier" : `${agent.model.kind}/${agent.model.model}`;
}

function renderPageSection(page: WikiPage | undefined, missingLabel: string): string {
  if (page === undefined) return `_No ${missingLabel} wiki page available._`;
  return `${page.digest}\n\n${page.body.trim()}`;
}

// `<projectDir>/AGENTS.md` — a single project-root file summarizing the
// generated harness for any agent CLI that reads the AGENTS.md convention.
// Section order and content are pinned by the M4 Task 5 brief: project
// summary (architecture page), build/test commands (build-and-test page),
// conventions (conventions page), then the agent roster table. The
// UNVERIFIED caveat is emitted directly under the title whenever
// `manifest.verification.evals !== "pass"` so it's the first thing a reader
// sees, not buried after the roster.
function renderAgentsMd(bundle: HarnessBundle): string {
  const lines: string[] = [];
  lines.push("# AGENTS.md");
  lines.push("");
  lines.push(
    "Generated by OpenFusion harness generation from this repository — a project-dedicated wiki, specialist agent roster, and routing policy. Regenerate via `engine.harness.generate` (or edit through the Harness editor) rather than hand-editing this file directly.",
  );
  lines.push("");

  if (bundle.manifest.verification.evals !== "pass") {
    lines.push(UNVERIFIED_CAVEAT);
    lines.push("");
  }

  lines.push("## Project summary");
  lines.push("");
  lines.push(renderPageSection(findPage(bundle, "architecture"), "architecture"));
  lines.push("");

  lines.push("## Build & test");
  lines.push("");
  lines.push(renderPageSection(findPage(bundle, "build-and-test"), "build-and-test"));
  lines.push("");

  lines.push("## Conventions");
  lines.push("");
  lines.push(renderPageSection(findPage(bundle, "conventions"), "conventions"));
  lines.push("");

  lines.push("## Agent roster");
  lines.push("");
  lines.push("| Name | Role | Task classes | Model |");
  lines.push("| --- | --- | --- | --- |");
  for (const agent of bundle.agents) {
    lines.push(`| ${agent.name} | ${agent.role} | ${agent.taskClasses.join(", ")} | ${renderModelHint(agent)} |`);
  }
  lines.push("");

  return lines.join("\n");
}

async function exportAgentsMd(projectDir: string, bundle: HarnessBundle): Promise<HarnessExportResult> {
  const filePath = path.join(projectDir, "AGENTS.md");
  await writeFile(filePath, renderAgentsMd(bundle), "utf8");
  return { files: [path.relative(projectDir, filePath)] };
}

// Read-only by default: an exported subagent runs on an open worker model
// under a specialist prompt this pipeline generated but has not yet
// eval-gated (see UNVERIFIED_CAVEAT above) — it should be able to explore
// the project, not mutate it, until a human explicitly widens its tools in
// Claude Code's own subagent config.
const READ_ONLY_TOOLS_LINE = "Read, Grep, Glob";

// `<projectDir>/.claude/agents/<name>.md` per agent — Claude Code's native
// subagent format: YAML frontmatter (name, description, a read-only tools
// default, and the model hint AS A COMMENT — see renderModelHint) followed
// by a blank line, the agent's own prompt, and a digest of every wiki page
// in the bundle so the subagent carries the same project context it would
// have had inside OpenFusion's own orchestrator, without requiring the wiki
// MCP server to be running.
function renderSubagentMd(agent: AgentDef, bundle: HarnessBundle): string {
  const frontmatter = stringifyYaml({
    name: agent.name,
    description: agent.description,
    tools: READ_ONLY_TOOLS_LINE,
  });
  const header = `---\n${frontmatter}# suggested worker: ${renderModelHint(agent)}\n---\n`;

  const body: string[] = [agent.prompt.trim(), "", "## Project wiki digest", ""];
  for (const page of bundle.pages) {
    body.push(`### ${page.title}`, "", page.digest, "");
  }

  return `${header}\n${body.join("\n").trimEnd()}\n`;
}

async function exportClaudeSubagents(projectDir: string, bundle: HarnessBundle): Promise<HarnessExportResult> {
  const dir = path.join(projectDir, ".claude", "agents");
  await mkdir(dir, { recursive: true });
  const files: string[] = [];
  for (const agent of bundle.agents) {
    const filePath = path.join(dir, `${agent.name}.md`);
    await writeFile(filePath, renderSubagentMd(agent, bundle), "utf8");
    files.push(path.relative(projectDir, filePath));
  }
  return { files };
}

// Entry point for `engine.harness.export` (methods.ts). Callers are
// responsible for loading and structurally validating the bundle first
// (loadHarness + validateHarness) — this function assumes `bundle` is
// already known-good and does no re-validation of its own.
export async function exportHarness(
  projectDir: string,
  bundle: HarnessBundle,
  format: HarnessExportFormat,
): Promise<HarnessExportResult> {
  if (format === "agents-md") return exportAgentsMd(projectDir, bundle);
  return exportClaudeSubagents(projectDir, bundle);
}
